# language: python
# python:
#   - "3.6"
# # command to install dependencies
# install:
#   - pip install -r requirements.txt
# # command to run tests
# script:
# - pytest


language: python

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up
env:
  global:
    - secure: ACCESS_TOKEN='721337135161352192-4iXqDquXow8XuZPdB8f1rDj9bnXm895'
    - secure: CONSUMER_API_KEY='og8QYT8YBJeHSz1yNLP7BiAZb'
    - secure: CONSUMER_API_SECRET='NiygKUg9hepRSriANonmvNrwEzY9tn1kPt1SKvknuAWQaIy8Cg'
    - secure: ACCESS_TOKEN_SECRET='wrCyczO5Zw4ze1VEsIji2DNgZROsiqdZRvOLYETTJF9W8'
  jobs:
  - USE_NETWORK=true
  - USE_NETWORK=false

# script:
#   - bundle exec rake test
