# language: python
# python:
#   - "3.6"
# # command to install dependencies
# install:
#   - pip install -r requirements.txt
# # command to run tests
# script:
# - pytest


language: python

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up

# script:
#   - bundle exec rake test
